<?php
/**
 * @file
 * upcoming_movie_trailers.features.field_base.inc
 */

/**
 * Implements hook_field_default_field_bases().
 */
function upcoming_movie_trailers_field_default_field_bases() {
  $field_bases = array();

  // Exported field_base: 'field_link'.
  $field_bases['field_link'] = array(
    'active' => 1,
    'cardinality' => 1,
    'deleted' => 0,
    'entity_types' => array(),
    'field_name' => 'field_link',
    'indexes' => array(),
    'locked' => 0,
    'module' => 'video_embed_field',
    'settings' => array(),
    'translatable' => 0,
    'type' => 'video_embed_field',
  );

  return $field_bases;
}
